runtime: php73

handlers:
# Serve a directory as a static resource.
- url: /swagger
  static_dir: public/swagger

- url: /mia-mail
  static_dir: public/mia-mail

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
  
env_variables:
  API_KEY: ""
  DB_HOST: ""
  DB_UNIXSOCKET: "/cloudsql/coinsport:asia-northeast3:coinsport-db"
  DB_DATABASE: "coinsport"
  DB_USERNAME: "root"
  DB_PASSWORD: "password"
  API_URL: "https://coinsport.du.r.appspot.com"
  SENDGRID_API_KEY: "KEY"
  SENDGRID_FROM: "info@coinposrt.com"
  SENDGRID_NAME: "CoinSport"
  SENDGRID_REPLY_TO: "info@coinsport.com"
  SENDGRID_BASE_URL: "https://coinsport.web.app/"